/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AppRouteImport } from './routes/app'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StrainsRouteImport } from './routes/strains'
import { Route as ApiApkRouteImport } from './routes/api/apk'
import { Route as ApiMobileSessionRouteImport } from './routes/api/mobile-session'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as AuthMobileRouteImport } from './routes/auth.mobile'
import { Route as StrainsStrainIdRouteImport } from './routes/strains.$strainId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StrainsRoute = StrainsRouteImport.update({
  id: '/strains',
  path: '/strains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkRoute = ApiApkRouteImport.update({
  id: '/api/apk',
  path: '/api/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSessionRoute = ApiMobileSessionRouteImport.update({
  id: '/api/mobile-session',
  path: '/api/mobile-session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMobileRoute = AuthMobileRouteImport.update({
  id: '/auth/mobile',
  path: '/auth/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const StrainsStrainIdRoute = StrainsStrainIdRouteImport.update({
  id: '/$strainId',
  path: '/$strainId',
  getParentRoute: () => StrainsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/app': typeof AppRoute
  '/evidence': typeof EvidenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/privacy': typeof PrivacyRoute
  '/strains': typeof StrainsRouteWithChildren
  '/api/apk': typeof ApiApkRoute
  '/api/mobile-session': typeof ApiMobileSessionRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/mobile': typeof AuthMobileRoute
  '/strains/$strainId': typeof StrainsStrainIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/app': typeof AppRoute
  '/evidence': typeof EvidenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/privacy': typeof PrivacyRoute
  '/strains': typeof StrainsRouteWithChildren
  '/api/apk': typeof ApiApkRoute
  '/api/mobile-session': typeof ApiMobileSessionRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/mobile': typeof AuthMobileRoute
  '/strains/$strainId': typeof StrainsStrainIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/app': typeof AppRoute
  '/evidence': typeof EvidenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/privacy': typeof PrivacyRoute
  '/strains': typeof StrainsRouteWithChildren
  '/api/apk': typeof ApiApkRoute
  '/api/mobile-session': typeof ApiMobileSessionRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/mobile': typeof AuthMobileRoute
  '/strains/$strainId': typeof StrainsStrainIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/app'
    | '/evidence'
    | '/knowledge'
    | '/library'
    | '/login'
    | '/patterns'
    | '/privacy'
    | '/strains'
    | '/api/apk'
    | '/api/mobile-session'
    | '/auth/google'
    | '/auth/mobile'
    | '/strains/$strainId'
    | '/api/auth/$'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/app'
    | '/evidence'
    | '/knowledge'
    | '/library'
    | '/login'
    | '/patterns'
    | '/privacy'
    | '/strains'
    | '/api/apk'
    | '/api/mobile-session'
    | '/auth/google'
    | '/auth/mobile'
    | '/strains/$strainId'
    | '/api/auth/$'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/app'
    | '/evidence'
    | '/knowledge'
    | '/library'
    | '/login'
    | '/patterns'
    | '/privacy'
    | '/strains'
    | '/api/apk'
    | '/api/mobile-session'
    | '/auth/google'
    | '/auth/mobile'
    | '/strains/$strainId'
    | '/api/auth/$'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AppRoute: typeof AppRoute
  EvidenceRoute: typeof EvidenceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PatternsRoute: typeof PatternsRoute
  PrivacyRoute: typeof PrivacyRoute
  StrainsRoute: typeof StrainsRouteWithChildren
  ApiApkRoute: typeof ApiApkRoute
  ApiMobileSessionRoute: typeof ApiMobileSessionRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  AuthMobileRoute: typeof AuthMobileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strains': {
      id: '/strains'
      path: '/strains'
      fullPath: '/strains'
      preLoaderRoute: typeof StrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk': {
      id: '/api/apk'
      path: '/api/apk'
      fullPath: '/api/apk'
      preLoaderRoute: typeof ApiApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-session': {
      id: '/api/mobile-session'
      path: '/api/mobile-session'
      fullPath: '/api/mobile-session'
      preLoaderRoute: typeof ApiMobileSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mobile': {
      id: '/auth/mobile'
      path: '/auth/mobile'
      fullPath: '/auth/mobile'
      preLoaderRoute: typeof AuthMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strains/$strainId': {
      id: '/strains/$strainId'
      path: '/$strainId'
      fullPath: '/strains/$strainId'
      preLoaderRoute: typeof StrainsStrainIdRouteImport
      parentRoute: typeof StrainsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StrainsRouteChildren {
  StrainsStrainIdRoute: typeof StrainsStrainIdRoute
}

const StrainsRouteChildren: StrainsRouteChildren = {
  StrainsStrainIdRoute: StrainsStrainIdRoute,
}

const StrainsRouteWithChildren =
  StrainsRoute._addFileChildren(StrainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AppRoute: AppRoute,
  EvidenceRoute: EvidenceRoute,
  KnowledgeRoute: KnowledgeRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PatternsRoute: PatternsRoute,
  PrivacyRoute: PrivacyRoute,
  StrainsRoute: StrainsRouteWithChildren,
  ApiApkRoute: ApiApkRoute,
  ApiMobileSessionRoute: ApiMobileSessionRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  AuthMobileRoute: AuthMobileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
