-- NOT APPLIED. PostgreSQL is NOT_CONFIGURED until DATABASE_URL exists.
-- SQLite data/gg-foundation.sqlite remains the scientific source of truth.
-- This file does not copy and does not modify the 8750800 measurements.

create table if not exists source_records (
  id bigint primary key,
  source_id text not null,
  source_record_id text not null,
  file_name text,
  row_number integer,
  original_name text,
  name_norm text,
  breeder text,
  lab text,
  independence_group text,
  sample_id text,
  tested_at text,
  content_hash text not null,
  match_status text not null
);

create table if not exists samples (
  id bigint primary key,
  source_record_id bigint not null references source_records(id),
  sample_key text,
  lab text,
  tested_at text,
  file_name text,
  row_number integer
);

create table if not exists measurements (
  id bigint primary key,
  source_record_id bigint not null references source_records(id),
  compound text not null,
  klass text,
  value double precision,
  unit text,
  qualifier text,
  analysis text,
  zero_semantics text,
  original_class text,
  normalized_class text,
  raw_cell_text text,
  raw_fidelity text,
  numeric_value double precision,
  value_status text,
  constraint measurement_qualifier_not_zero check (qualifier is null or value is null)
);

create table if not exists canonical_entities (
  id bigint primary key,
  entity_key text not null unique,
  display_name text not null,
  name_norm text not null,
  breeder text,
  identity_status text not null
);

create table if not exists aliases (
  id bigint primary key,
  canonical_id bigint not null references canonical_entities(id),
  source_record_id bigint not null references source_records(id),
  alias text not null,
  alias_norm text not null
);

create table if not exists pedigree_edges (
  id bigint primary key,
  child_record_id bigint not null references source_records(id),
  child_canonical_id bigint references canonical_entities(id),
  parent_text text not null,
  parent_norm text not null,
  parent_canonical_id bigint references canonical_entities(id),
  relationship_type text not null,
  identity_status text not null,
  score_kind text,
  reported_or_inferred text,
  snapshot_id text
);

create table if not exists claims (
  id bigint primary key,
  source_record_id bigint references source_records(id),
  field text not null,
  value text,
  claim_class text not null default 'UNVERIFIED'
);

create table if not exists identity_decisions (
  source_record_id bigint not null references source_records(id),
  status text not null,
  method text not null,
  heuristic_score double precision,
  score_kind text not null,
  resolver_version text not null,
  decided_at text not null,
  explanation text not null,
  created_snapshot_id text,
  review_status text,
  scientific_status text,
  human_review_required integer,
  human_review_status text
);

create table if not exists identity_resolution (
  source_record_id bigint not null references source_records(id),
  status text not null,
  canonical_id bigint references canonical_entities(id),
  prior_status text not null
);

create table if not exists entity_links (
  source_record_id bigint not null references source_records(id),
  canonical_id bigint references canonical_entities(id),
  match_status text not null
);

create table if not exists knowledge_snapshots (
  snapshot_id text primary key,
  raw_records integer not null,
  measurements integer not null,
  note text not null
);

create table if not exists research_events (
  id text primary key,
  research_key text not null,
  query text not null,
  normalized_query text not null,
  query_kind text not null,
  status text not null,
  prompt_version text not null,
  grok_called integer not null,
  snapshot_before text not null
);

create table if not exists jobs (
  id bigint generated by default as identity primary key,
  job_type text not null,
  job_status text not null,
  input_snapshot text,
  input_hash text,
  owner_token text,
  lease_until text,
  retry_count integer not null default 0,
  error text
);

create table if not exists observation_units (
  source_record_id bigint references source_records(id),
  unit_kind text not null,
  independence_group text not null,
  dataset_id text not null,
  lab text,
  sample_key text,
  tested_at text
);

create table if not exists pattern_candidates (
  id bigint primary key,
  pattern_key text not null,
  hypothesis text not null,
  lifecycle text not null,
  promoted_to_validated integer not null
);

create table if not exists model_versions (
  model_id text not null,
  version text not null,
  algorithm text not null,
  training_snapshot text,
  calibration_status text,
  status text not null,
  production_eligible integer not null,
  primary key (model_id, version)
);

create table if not exists calibration_runs (
  calibration_id text primary key,
  model_id text not null,
  method text,
  status text not null,
  coverage double precision,
  snapshot_id text not null
);

create table if not exists calibration_metrics (
  calibration_id text not null references calibration_runs(calibration_id),
  metric text not null,
  value double precision,
  primary key (calibration_id, metric)
);

create table if not exists calibration_bins (
  calibration_id text not null references calibration_runs(calibration_id),
  bin_index integer not null,
  mean_predicted double precision,
  fraction_positive double precision,
  count integer not null,
  primary key (calibration_id, bin_index)
);

create table if not exists catalog_gaps (
  id bigint primary key,
  source_id text not null,
  declared_rows integer not null,
  records_in_file integer not null,
  gap_count integer not null,
  reason_code text not null
);

create index if not exists measurements_source_record_idx on measurements (source_record_id);
create index if not exists samples_source_record_idx on samples (source_record_id);
create index if not exists aliases_canonical_idx on aliases (canonical_id);
create index if not exists pedigree_child_idx on pedigree_edges (child_canonical_id);
create index if not exists jobs_status_idx on jobs (job_status, job_type);
