-- NOT APPLIED. READY_TO_APPLY only. Requires DATABASE_URL.
-- Does not read or write data/gg-foundation.sqlite.
-- AI rows may enter only as UNVERIFIED_AI_RESEARCH.

create table if not exists global_research_memory (
  id bigint generated by default as identity primary key,
  lookup_key text not null,
  normalized_query text not null,
  research_scope text not null,
  snapshot_id text not null,
  provider text not null,
  model text,
  status text not null default 'UNVERIFIED_AI_RESEARCH',
  provenance jsonb not null,
  response_json jsonb not null,
  created_at timestamptz not null default now(),
  constraint global_memory_unverified check (
    status in ('UNVERIFIED_AI_RESEARCH', 'STALE', 'SUPERSEDED', 'REVOKED')
  ),
  unique (lookup_key, research_scope, snapshot_id)
);

create index if not exists global_research_memory_query_idx
  on global_research_memory (normalized_query, research_scope);

create table if not exists private_user_memory (
  id bigint generated by default as identity primary key,
  user_id text not null,
  normalized_query text not null,
  body jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists private_user_memory_owner_idx
  on private_user_memory (user_id, normalized_query);

alter table private_user_memory enable row level security;

create table if not exists worker_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null,
  job_status text not null,
  idempotency_key text not null unique,
  owner_token text,
  lease_until timestamptz,
  retry_count integer not null default 0,
  error text,
  constraint worker_job_status check (
    job_status in ('QUEUED', 'RUNNING', 'SUCCEEDED', 'RETRYABLE', 'FAILED', 'DEAD_LETTER', 'CANCELLED')
  )
);

create index if not exists worker_jobs_claim_idx
  on worker_jobs (job_status, id);
