create table if not exists corpus_audit (
  id bigint generated by default as identity primary key,
  snapshot_id text not null,
  source_records bigint not null,
  samples bigint not null,
  measurements bigint not null,
  numeric_values bigint not null,
  qualified_measurements bigint not null,
  canonical_entities bigint not null,
  distinct_names bigint not null,
  aliases bigint not null,
  claims bigint not null,
  pedigree_edges bigint not null,
  external_rows_added bigint not null,
  prediction_status text not null,
  created_at timestamptz not null default now()
);
